framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - vendor/php-flasher/flasher/Resources/public/
        missing_import_mode: warn

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
