controllers_account:
    resource:
        path: ../src/Identity/Ui/
        namespace: App\Identity\Ui
    prefix: /api/v1
    type: attribute
controllers_projects:
    resource:
        path: ../src/Projects/Ui/
        namespace: App\Projects\Ui
    prefix: /api/v1
    type: attribute
controllers_logging:
    resource:
        path: ../src/Logging/Ui/
        namespace: App\Logging\Ui
    prefix: /api/v1
    type: attribute
translation_controller:
    resource:
        path: ../src/Kernel/Translator/
        namespace: App\Kernel\Translator
    prefix: /api/v1
    type: attribute